action_id: trunk-whoami
date: 2024-06-07 09:38:13
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1717753093
full_timestamp:
  nanos: 605144000
  seconds: 1717753093
trunk_version: 1.22.1
